config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  before_create do
    self.posts_counter = 0
  end

  def recent_posts
    posts.includes(:author, :likes, :comments).order(created_at: :desc).limit(3)
  end
  ## CanCan Roles
  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<section class="users-list">
  <%= button_to "Logout", destroy_user_session_path, class:"link", method: :delete %>
  <%= render partial: "shared/user", collection: @users %>
</section>

app/views/users/show.html.erb
<section class="user">
  <%= render partial: "shared/back", locals: {back:users_path} %>
  <%= render partial: "shared/user", locals: {user: @user_current} %>
  <div class="user-bio container">
    <h3 class="user-container_heading">Bio</h3>
    <p class="user-container_text"><%= @user_current.bio %></p>
  </div>
  <%= render partial: "shared/post", collection: @user_current.recent_posts %>
  <button class="see-all"><%= link_to "See all posts", user_posts_path(params[:id]), class:"link-to_user" %></button>
</section>