config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

  

app/views/shared/_back.html.erb
<%= link_to back, class:"link-back link" do %>
  <i class="fa fa-arrow-left"></i>
<% end %>

app/views/shared/_comment.html.erb
<div class="comment">
  <p><%= comment.author.name %>:
    <span><%= comment.text %></span></p>
  <%= button_to user_post_comment_path(user_id: comment.post.author_id, post_id: comment.post_id, id: comment.id), class:"link", method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
</div>

app/views/shared/_comment_form.html.erb
<%= form_with model:Comment.new,  url: user_post_comments_path(user_id: user_id, post_id:post_id), class: "comment-form", scope: :comment do |form| %>
  <%= form.text_area :text, class:"comment-form_text", placeholder: "Add comment ..." %>
  <%= form.submit "Comment", class: "submit-comment" %>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id =>  "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/shared/_like_form.html.erb
<%= form_with Model: Like.new, url: user_post_likes_path(user_id: user_id,post_id: post_id), class: "like-form", scope: :like do |form| %>
  <%= button_tag type: 'submit', class: "heart" do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/shared/_post.html.erb
<div class="user-posts container">
  <h3 class="user-container_heading"><%= post.title %>
    #<%= post.id %></h3>
  <p class="user-container_text"><%= truncate(post.text, :length => 50) %></p>
  <div class="user-container_misc">
    <div class="blog-btn-container">
      <%= link_to "See Post", user_post_path(user_id: post.author_id, id: post.id), class:"link" %>
      <% if can? :destroy, post %>
        <%= button_to "Delete Post", user_post_path(user_id: post.author_id, id: post.id), class:"link", method: :delete %>
      <% end %>
    </div>
    <div class="user-posts_stats">
      <p>Comments:
        <%= post.comments_counter %></p>
      <p>Likes:
        <%= post.likes_counter %></p>
      <%= render partial: "shared/like_form", locals: {user_id: post.author_id, post_id: post.id} %>
    </div>
  </div>
</div>

app/views/shared/_post_form.html.erb
<section class="new-post">
<%= render partial: "shared/back", locals: {back:user_posts_path}%>
  <h1 class="new-post_heading">Create a New Post</h1>
    <%=  form_with model:new_post, url: user_posts_url(user_id: current_user_id), class: "new-post_form" do |form| %>

      <div class= new-post_title >
        <%= form.label :title, "Title: "  %> 
        <%= form.text_field :title, autofocus: true %>
      </div>

      <div class= "new-post_desc" >
        <%= form.label :text, "Content: " %> 
        <%= form.text_area :text ,rows:5,  cols: 100 %>
      </div>

      <%= form.submit "Submit", class:"submit-post" %>
    <% end %>
</section>

app/views/shared/_user.html.erb
<div class="users-list_user">
  <div class="users-list_img">
    <img src=<%= user.photo %> alt="">
  </div>
  <div class="users-list_desc">
    <%= link_to user_path(user.id), class:"link-to_user" do %>
      <h2 class="users-list_name"><%= user.name %></h2>
    <% end %>
    <p class="users-list_posts">Number of Posts:
      <%= user.posts_counter %></p>
  </div>
</div>